2022-01-28 08:08:50,383 Downloading artifact
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Project hitoshikumagai/exercise_4 does not contain artifact: "genrs_mod.parquet:latest"
Traceback (most recent call last):
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 761, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 3443, in __init__
    self._load()
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 3961, in _load
    raise ValueError(
ValueError: Project hitoshikumagai/exercise_4 does not contain artifact: "genrs_mod.parquet:latest"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 72, in <module>
    go(args)
  File "run.py", line 18, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2414, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/kumagaihitoshi/.local/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 761, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 3443, in __init__
    self._load()
  File "/Users/kumagaihitoshi/.conda/envs/mlflow-2c6e6e31c4b7c87c9e59aeb22d34fcd10b15af54/lib/python3.8/site-packages/wandb/apis/public.py", line 3961, in _load
    raise ValueError(
wandb.errors.CommError: Project hitoshikumagai/exercise_4 does not contain artifact: "genrs_mod.parquet:latest"